config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get '/tasks', to: 'tasks#index'

  # get '/tasks/new', to: 'tasks#new'
  # post '/tasks', to: 'tasks#create'

  # get '/tasks', to: 'tasks#index'
  # get '/tasks/:id', to: 'tasks#show', as: :task

  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch 'tasks/:id', to: 'tasks#update'

  # delete '/tasks/:id', to: 'tasks#destroy'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details%>
<%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit this Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Go Back', tasks_path(@task) %>

app/views/tasks/index.html.erb
<h1>Index</h1>

<% @tasks.each do |task| %>
<%# <li><% task.title %></li>
  <li><%= link_to task.title, task_path(task) %>
  <%= link_to "Delete",
  task_path(task.id),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
  </li>


<% end %>

<%= link_to 'Create a Task', new_task_path(@task) %>

app/views/tasks/new.html.erb
<h1>Create New</h1>

<%= render 'form', task: @task %>

<%= link_to 'Go Back', tasks_path(@task) %>

app/views/tasks/show.html.erb
<h1><%= @tasks.title %></h1>
<p><%= @tasks.details %></p>

<%= link_to 'Edit this Task', edit_task_path(@task) %>
<%= link_to 'Go Back', tasks_path(@task) %>